### ISSUE TITLE
cleaning up .webhook ends in error due to it being a folder

### ISSUE THREAD

**Issue by chughesvf** [dashcheulov/r10k-webhook#3]
`Traceback (most recent call last):
  File "/usr/local/bin/r10k_daemon", line 11, in <module>
    load_entry_point('r10k-webhook==0.1.1', 'console_scripts', 'r10k_daemon')()
  File "/usr/local/lib/python3.6/dist-packages/r10kwebhook/__init__.py", line 316, in entry
    return cls().run()
  File "/usr/local/lib/python3.6/dist-packages/r10kwebhook/__init__.py", line 253, in __init__
    if self._r10k.deploy_env() == 'err':
  File "/usr/local/lib/python3.6/dist-packages/r10kwebhook/__init__.py", line 117, in deploy_env
    sync_output = self._sync_dirs()
  File "/usr/local/lib/python3.6/dist-packages/r10kwebhook/__init__.py", line 160, in _sync_dirs
    os.remove(os.path.join(basedir, dst_dir))
IsADirectoryError: [Errno 21] Is a directory: '/var/lib/docker/volumes/pupperware_puppetserver-code/_data/environments/.webhook'`

**Comment by chughesvf** [comment]
this may be a result of running the daemon on the CLI. I don't see it after stopping the service:

`May 29 09:40:25 mintd r10k_daemon[2792]: INFO: Removing symlink /var/lib/docker/volumes/pupperware_puppetserver-code/_data/environments/.webhook`
